let
    Source = Json.Document(File.Contents("Z:\powerbi\powerbi\openpsychometrics__ambi_dec_2019\data\question_map.json")),
    #"Converted to Table" = Table.FromRecords({Source}),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Q1", type text}, {"Q2", type text}, {"Q3", type text}, {"Q4", type text}, {"Q5", type text}, {"Q6", type text}, {"Q7", type text}, {"Q8", type text}, {"Q9", type text}, {"Q10", type text}, {"Q11", type text}, {"Q12", type text}, {"Q13", type text}, {"Q14", type text}, {"Q15", type text}, {"Q16", type text}, {"Q17", type text}, {"Q18", type text}, {"Q19", type text}, {"Q20", type text}, {"Q21", type text}, {"Q22", type text}, {"Q23", type text}, {"Q24", type text}, {"Q25", type text}, {"Q26", type text}, {"Q27", type text}, {"Q28", type text}, {"Q29", type text}, {"Q30", type text}, {"Q31", type text}, {"Q32", type text}, {"Q33", type text}, {"Q34", type text}, {"Q35", type text}, {"Q36", type text}, {"Q37", type text}, {"Q38", type text}, {"Q39", type text}, {"Q40", type text}, {"Q41", type text}, {"Q42", type text}, {"Q43", type text}, {"Q44", type text}, {"Q45", type text}, {"Q46", type text}, {"Q47", type text}, {"Q48", type text}, {"Q49", type text}, {"Q50", type text}, {"Q51", type text}, {"Q52", type text}, {"Q53", type text}, {"Q54", type text}, {"Q55", type text}, {"Q56", type text}, {"Q57", type text}, {"Q58", type text}, {"Q59", type text}, {"Q60", type text}, {"Q61", type text}, {"Q62", type text}, {"Q63", type text}, {"Q64", type text}, {"Q65", type text}, {"Q66", type text}, {"Q67", type text}, {"Q68", type text}, {"Q69", type text}, {"Q70", type text}, {"Q71", type text}, {"Q72", type text}, {"Q73", type text}, {"Q74", type text}, {"Q75", type text}, {"Q76", type text}, {"Q77", type text}, {"Q78", type text}, {"Q79", type text}, {"Q80", type text}, {"Q81", type text}, {"Q82", type text}, {"Q83", type text}, {"Q84", type text}, {"Q85", type text}, {"Q86", type text}, {"Q87", type text}, {"Q88", type text}, {"Q89", type text}, {"Q90", type text}, {"Q91", type text}, {"Q92", type text}, {"Q93", type text}, {"Q94", type text}, {"Q95", type text}, {"Q96", type text}, {"Q97", type text}, {"Q98", type text}, {"Q99", type text}, {"Q100", type text}, {"Q101", type text}, {"Q102", type text}, {"Q103", type text}, {"Q104", type text}, {"Q105", type text}, {"Q106", type text}, {"Q107", type text}, {"Q108", type text}, {"Q109", type text}, {"Q110", type text}, {"Q111", type text}, {"Q112", type text}, {"Q113", type text}, {"Q114", type text}, {"Q115", type text}, {"Q116", type text}, {"Q117", type text}, {"Q118", type text}, {"Q119", type text}, {"Q120", type text}, {"Q121", type text}, {"Q122", type text}, {"Q123", type text}, {"Q124", type text}, {"Q125", type text}, {"Q126", type text}, {"Q127", type text}, {"Q128", type text}, {"Q129", type text}, {"Q130", type text}, {"Q131", type text}, {"Q132", type text}, {"Q133", type text}, {"Q134", type text}, {"Q135", type text}, {"Q136", type text}, {"Q137", type text}, {"Q138", type text}, {"Q139", type text}, {"Q140", type text}, {"Q141", type text}, {"Q142", type text}, {"Q143", type text}, {"Q144", type text}, {"Q145", type text}, {"Q146", type text}, {"Q147", type text}, {"Q148", type text}, {"Q149", type text}, {"Q150", type text}, {"Q151", type text}, {"Q152", type text}, {"Q153", type text}, {"Q154", type text}, {"Q155", type text}, {"Q156", type text}, {"Q157", type text}, {"Q158", type text}, {"Q159", type text}, {"Q160", type text}, {"Q161", type text}, {"Q162", type text}, {"Q163", type text}, {"Q164", type text}, {"Q165", type text}, {"Q166", type text}, {"Q167", type text}, {"Q168", type text}, {"Q169", type text}, {"Q170", type text}, {"Q171", type text}, {"Q172", type text}, {"Q173", type text}, {"Q174", type text}, {"Q175", type text}, {"Q176", type text}, {"Q177", type text}, {"Q178", type text}, {"Q179", type text}, {"Q180", type text}, {"Q181", type text}}),
    
    RenamedColumns = Table.RenameColumns(#"Changed Type",
        List.Transform(Table.ColumnNames(#"Changed Type"),
            each if Text.StartsWith(_, "Q") and Text.Length(_) > 1 and Text.Middle(_, 1, Text.Length(_) - 1) = Text.Select(Text.Middle(_, 1, Text.Length(_) - 1), {"0".."9"})
                then {_, Text.Middle(_, 1)} else {_, _}
        )
    ),

    #"Demoted Headers" = Table.DemoteHeaders(RenamedColumns),


    #"Changed the type of new headers" = Table.TransformColumnTypes(#"Demoted Headers",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column54", type text}, {"Column55", type text}, {"Column56", type text}, {"Column57", type text}, {"Column58", type text}, {"Column59", type text}, {"Column60", type text}, {"Column61", type text}, {"Column62", type text}, {"Column63", type text}, {"Column64", type text}, {"Column65", type text}, {"Column66", type text}, {"Column67", type text}, {"Column68", type text}, {"Column69", type text}, {"Column70", type text}, {"Column71", type text}, {"Column72", type text}, {"Column73", type text}, {"Column74", type text}, {"Column75", type text}, {"Column76", type text}, {"Column77", type text}, {"Column78", type text}, {"Column79", type text}, {"Column80", type text}, {"Column81", type text}, {"Column82", type text}, {"Column83", type text}, {"Column84", type text}, {"Column85", type text}, {"Column86", type text}, {"Column87", type text}, {"Column88", type text}, {"Column89", type text}, {"Column90", type text}, {"Column91", type text}, {"Column92", type text}, {"Column93", type text}, {"Column94", type text}, {"Column95", type text}, {"Column96", type text}, {"Column97", type text}, {"Column98", type text}, {"Column99", type text}, {"Column100", type text}, {"Column101", type text}, {"Column102", type text}, {"Column103", type text}, {"Column104", type text}, {"Column105", type text}, {"Column106", type text}, {"Column107", type text}, {"Column108", type text}, {"Column109", type text}, {"Column110", type text}, {"Column111", type text}, {"Column112", type text}, {"Column113", type text}, {"Column114", type text}, {"Column115", type text}, {"Column116", type text}, {"Column117", type text}, {"Column118", type text}, {"Column119", type text}, {"Column120", type text}, {"Column121", type text}, {"Column122", type text}, {"Column123", type text}, {"Column124", type text}, {"Column125", type text}, {"Column126", type text}, {"Column127", type text}, {"Column128", type text}, {"Column129", type text}, {"Column130", type text}, {"Column131", type text}, {"Column132", type text}, {"Column133", type text}, {"Column134", type text}, {"Column135", type text}, {"Column136", type text}, {"Column137", type text}, {"Column138", type text}, {"Column139", type text}, {"Column140", type text}, {"Column141", type text}, {"Column142", type text}, {"Column143", type text}, {"Column144", type text}, {"Column145", type text}, {"Column146", type text}, {"Column147", type text}, {"Column148", type text}, {"Column149", type text}, {"Column150", type text}, {"Column151", type text}, {"Column152", type text}, {"Column153", type text}, {"Column154", type text}, {"Column155", type text}, {"Column156", type text}, {"Column157", type text}, {"Column158", type text}, {"Column159", type text}, {"Column160", type text}, {"Column161", type text}, {"Column162", type text}, {"Column163", type text}, {"Column164", type text}, {"Column165", type text}, {"Column166", type text}, {"Column167", type text}, {"Column168", type text}, {"Column169", type text}, {"Column170", type text}, {"Column171", type text}, {"Column172", type text}, {"Column173", type text}, {"Column174", type text}, {"Column175", type text}, {"Column176", type text}, {"Column177", type text}, {"Column178", type text}, {"Column179", type text}, {"Column180", type text}, {"Column181", type text}}),
    #"Transposed Table" = Table.Transpose(#"Changed the type of new headers"),
    #"Renamed Columns" = Table.RenameColumns(#"Transposed Table",{{"Column1", "qid"}, {"Column2", "question"}})
    
in
    #"Renamed Columns"
