let
    Source = Csv.Document(File.Contents("Z:\powerbi\powerbi\openpsychometrics__ambi_dec_2019\data\data.csv"),[Delimiter="	", Columns=543, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Q1A", Int64.Type}, {"Q1I", Int64.Type}, {"Q1E", Int64.Type}, {"Q2A", Int64.Type}, {"Q2I", Int64.Type}, {"Q2E", Int64.Type}, {"Q3A", Int64.Type}, {"Q3I", Int64.Type}, {"Q3E", Int64.Type}, {"Q4A", Int64.Type}, {"Q4I", Int64.Type}, {"Q4E", Int64.Type}, {"Q5A", Int64.Type}, {"Q5I", Int64.Type}, {"Q5E", Int64.Type}, {"Q6A", Int64.Type}, {"Q6I", Int64.Type}, {"Q6E", Int64.Type}, {"Q7A", Int64.Type}, {"Q7I", Int64.Type}, {"Q7E", Int64.Type}, {"Q8A", Int64.Type}, {"Q8I", Int64.Type}, {"Q8E", Int64.Type}, {"Q9A", Int64.Type}, {"Q9I", Int64.Type}, {"Q9E", Int64.Type}, {"Q10A", Int64.Type}, {"Q10I", Int64.Type}, {"Q10E", Int64.Type}, {"Q11A", Int64.Type}, {"Q11I", Int64.Type}, {"Q11E", Int64.Type}, {"Q12A", Int64.Type}, {"Q12I", Int64.Type}, {"Q12E", Int64.Type}, {"Q13A", Int64.Type}, {"Q13I", Int64.Type}, {"Q13E", Int64.Type}, {"Q14A", Int64.Type}, {"Q14I", Int64.Type}, {"Q14E", Int64.Type}, {"Q15A", Int64.Type}, {"Q15I", Int64.Type}, {"Q15E", Int64.Type}, {"Q16A", Int64.Type}, {"Q16I", Int64.Type}, {"Q16E", Int64.Type}, {"Q17A", Int64.Type}, {"Q17I", Int64.Type}, {"Q17E", Int64.Type}, {"Q18A", Int64.Type}, {"Q18I", Int64.Type}, {"Q18E", Int64.Type}, {"Q19A", Int64.Type}, {"Q19I", Int64.Type}, {"Q19E", Int64.Type}, {"Q20A", Int64.Type}, {"Q20I", Int64.Type}, {"Q20E", Int64.Type}, {"Q21A", Int64.Type}, {"Q21I", Int64.Type}, {"Q21E", Int64.Type}, {"Q22A", Int64.Type}, {"Q22I", Int64.Type}, {"Q22E", Int64.Type}, {"Q23A", Int64.Type}, {"Q23I", Int64.Type}, {"Q23E", Int64.Type}, {"Q24A", Int64.Type}, {"Q24I", Int64.Type}, {"Q24E", Int64.Type}, {"Q25A", Int64.Type}, {"Q25I", Int64.Type}, {"Q25E", Int64.Type}, {"Q26A", Int64.Type}, {"Q26I", Int64.Type}, {"Q26E", Int64.Type}, {"Q27A", Int64.Type}, {"Q27I", Int64.Type}, {"Q27E", Int64.Type}, {"Q28A", Int64.Type}, {"Q28I", Int64.Type}, {"Q28E", Int64.Type}, {"Q29A", Int64.Type}, {"Q29I", Int64.Type}, {"Q29E", Int64.Type}, {"Q30A", Int64.Type}, {"Q30I", Int64.Type}, {"Q30E", Int64.Type}, {"Q31A", Int64.Type}, {"Q31I", Int64.Type}, {"Q31E", Int64.Type}, {"Q32A", Int64.Type}, {"Q32I", Int64.Type}, {"Q32E", Int64.Type}, {"Q33A", Int64.Type}, {"Q33I", Int64.Type}, {"Q33E", Int64.Type}, {"Q34A", Int64.Type}, {"Q34I", Int64.Type}, {"Q34E", Int64.Type}, {"Q35A", Int64.Type}, {"Q35I", Int64.Type}, {"Q35E", Int64.Type}, {"Q36A", Int64.Type}, {"Q36I", Int64.Type}, {"Q36E", Int64.Type}, {"Q37A", Int64.Type}, {"Q37I", Int64.Type}, {"Q37E", Int64.Type}, {"Q38A", Int64.Type}, {"Q38I", Int64.Type}, {"Q38E", Int64.Type}, {"Q39A", Int64.Type}, {"Q39I", Int64.Type}, {"Q39E", Int64.Type}, {"Q40A", Int64.Type}, {"Q40I", Int64.Type}, {"Q40E", Int64.Type}, {"Q41A", Int64.Type}, {"Q41I", Int64.Type}, {"Q41E", Int64.Type}, {"Q42A", Int64.Type}, {"Q42I", Int64.Type}, {"Q42E", Int64.Type}, {"Q43A", Int64.Type}, {"Q43I", Int64.Type}, {"Q43E", Int64.Type}, {"Q44A", Int64.Type}, {"Q44I", Int64.Type}, {"Q44E", Int64.Type}, {"Q45A", Int64.Type}, {"Q45I", Int64.Type}, {"Q45E", Int64.Type}, {"Q46A", Int64.Type}, {"Q46I", Int64.Type}, {"Q46E", Int64.Type}, {"Q47A", Int64.Type}, {"Q47I", Int64.Type}, {"Q47E", Int64.Type}, {"Q48A", Int64.Type}, {"Q48I", Int64.Type}, {"Q48E", Int64.Type}, {"Q49A", Int64.Type}, {"Q49I", Int64.Type}, {"Q49E", Int64.Type}, {"Q50A", Int64.Type}, {"Q50I", Int64.Type}, {"Q50E", Int64.Type}, {"Q51A", Int64.Type}, {"Q51I", Int64.Type}, {"Q51E", Int64.Type}, {"Q52A", Int64.Type}, {"Q52I", Int64.Type}, {"Q52E", Int64.Type}, {"Q53A", Int64.Type}, {"Q53I", Int64.Type}, {"Q53E", Int64.Type}, {"Q54A", Int64.Type}, {"Q54I", Int64.Type}, {"Q54E", Int64.Type}, {"Q55A", Int64.Type}, {"Q55I", Int64.Type}, {"Q55E", Int64.Type}, {"Q56A", Int64.Type}, {"Q56I", Int64.Type}, {"Q56E", Int64.Type}, {"Q57A", Int64.Type}, {"Q57I", Int64.Type}, {"Q57E", Int64.Type}, {"Q58A", Int64.Type}, {"Q58I", Int64.Type}, {"Q58E", Int64.Type}, {"Q59A", Int64.Type}, {"Q59I", Int64.Type}, {"Q59E", Int64.Type}, {"Q60A", Int64.Type}, {"Q60I", Int64.Type}, {"Q60E", Int64.Type}, {"Q61A", Int64.Type}, {"Q61I", Int64.Type}, {"Q61E", Int64.Type}, {"Q62A", Int64.Type}, {"Q62I", Int64.Type}, {"Q62E", Int64.Type}, {"Q63A", Int64.Type}, {"Q63I", Int64.Type}, {"Q63E", Int64.Type}, {"Q64A", Int64.Type}, {"Q64I", Int64.Type}, {"Q64E", Int64.Type}, {"Q65A", Int64.Type}, {"Q65I", Int64.Type}, {"Q65E", Int64.Type}, {"Q66A", Int64.Type}, {"Q66I", Int64.Type}, {"Q66E", Int64.Type}, {"Q67A", Int64.Type}, {"Q67I", Int64.Type}, {"Q67E", Int64.Type}, {"Q68A", Int64.Type}, {"Q68I", Int64.Type}, {"Q68E", Int64.Type}, {"Q69A", Int64.Type}, {"Q69I", Int64.Type}, {"Q69E", Int64.Type}, {"Q70A", Int64.Type}, {"Q70I", Int64.Type}, {"Q70E", Int64.Type}, {"Q71A", Int64.Type}, {"Q71I", Int64.Type}, {"Q71E", Int64.Type}, {"Q72A", Int64.Type}, {"Q72I", Int64.Type}, {"Q72E", Int64.Type}, {"Q73A", Int64.Type}, {"Q73I", Int64.Type}, {"Q73E", Int64.Type}, {"Q74A", Int64.Type}, {"Q74I", Int64.Type}, {"Q74E", Int64.Type}, {"Q75A", Int64.Type}, {"Q75I", Int64.Type}, {"Q75E", Int64.Type}, {"Q76A", Int64.Type}, {"Q76I", Int64.Type}, {"Q76E", Int64.Type}, {"Q77A", Int64.Type}, {"Q77I", Int64.Type}, {"Q77E", Int64.Type}, {"Q78A", Int64.Type}, {"Q78I", Int64.Type}, {"Q78E", Int64.Type}, {"Q79A", Int64.Type}, {"Q79I", Int64.Type}, {"Q79E", Int64.Type}, {"Q80A", Int64.Type}, {"Q80I", Int64.Type}, {"Q80E", Int64.Type}, {"Q81A", Int64.Type}, {"Q81I", Int64.Type}, {"Q81E", Int64.Type}, {"Q82A", Int64.Type}, {"Q82I", Int64.Type}, {"Q82E", Int64.Type}, {"Q83A", Int64.Type}, {"Q83I", Int64.Type}, {"Q83E", Int64.Type}, {"Q84A", Int64.Type}, {"Q84I", Int64.Type}, {"Q84E", Int64.Type}, {"Q85A", Int64.Type}, {"Q85I", Int64.Type}, {"Q85E", Int64.Type}, {"Q86A", Int64.Type}, {"Q86I", Int64.Type}, {"Q86E", Int64.Type}, {"Q87A", Int64.Type}, {"Q87I", Int64.Type}, {"Q87E", Int64.Type}, {"Q88A", Int64.Type}, {"Q88I", Int64.Type}, {"Q88E", Int64.Type}, {"Q89A", Int64.Type}, {"Q89I", Int64.Type}, {"Q89E", Int64.Type}, {"Q90A", Int64.Type}, {"Q90I", Int64.Type}, {"Q90E", Int64.Type}, {"Q91A", Int64.Type}, {"Q91I", Int64.Type}, {"Q91E", Int64.Type}, {"Q92A", Int64.Type}, {"Q92I", Int64.Type}, {"Q92E", Int64.Type}, {"Q93A", Int64.Type}, {"Q93I", Int64.Type}, {"Q93E", Int64.Type}, {"Q94A", Int64.Type}, {"Q94I", Int64.Type}, {"Q94E", Int64.Type}, {"Q95A", Int64.Type}, {"Q95I", Int64.Type}, {"Q95E", Int64.Type}, {"Q96A", Int64.Type}, {"Q96I", Int64.Type}, {"Q96E", Int64.Type}, {"Q97A", Int64.Type}, {"Q97I", Int64.Type}, {"Q97E", Int64.Type}, {"Q98A", Int64.Type}, {"Q98I", Int64.Type}, {"Q98E", Int64.Type}, {"Q99A", Int64.Type}, {"Q99I", Int64.Type}, {"Q99E", Int64.Type}, {"Q100A", Int64.Type}, {"Q100I", Int64.Type}, {"Q100E", Int64.Type}, {"Q101A", Int64.Type}, {"Q101I", Int64.Type}, {"Q101E", Int64.Type}, {"Q102A", Int64.Type}, {"Q102I", Int64.Type}, {"Q102E", Int64.Type}, {"Q103A", Int64.Type}, {"Q103I", Int64.Type}, {"Q103E", Int64.Type}, {"Q104A", Int64.Type}, {"Q104I", Int64.Type}, {"Q104E", Int64.Type}, {"Q105A", Int64.Type}, {"Q105I", Int64.Type}, {"Q105E", Int64.Type}, {"Q106A", Int64.Type}, {"Q106I", Int64.Type}, {"Q106E", Int64.Type}, {"Q107A", Int64.Type}, {"Q107I", Int64.Type}, {"Q107E", Int64.Type}, {"Q108A", Int64.Type}, {"Q108I", Int64.Type}, {"Q108E", Int64.Type}, {"Q109A", Int64.Type}, {"Q109I", Int64.Type}, {"Q109E", Int64.Type}, {"Q110A", Int64.Type}, {"Q110I", Int64.Type}, {"Q110E", Int64.Type}, {"Q111A", Int64.Type}, {"Q111I", Int64.Type}, {"Q111E", Int64.Type}, {"Q112A", Int64.Type}, {"Q112I", Int64.Type}, {"Q112E", Int64.Type}, {"Q113A", Int64.Type}, {"Q113I", Int64.Type}, {"Q113E", Int64.Type}, {"Q114A", Int64.Type}, {"Q114I", Int64.Type}, {"Q114E", Int64.Type}, {"Q115A", Int64.Type}, {"Q115I", Int64.Type}, {"Q115E", Int64.Type}, {"Q116A", Int64.Type}, {"Q116I", Int64.Type}, {"Q116E", Int64.Type}, {"Q117A", Int64.Type}, {"Q117I", Int64.Type}, {"Q117E", Int64.Type}, {"Q118A", Int64.Type}, {"Q118I", Int64.Type}, {"Q118E", Int64.Type}, {"Q119A", Int64.Type}, {"Q119I", Int64.Type}, {"Q119E", Int64.Type}, {"Q120A", Int64.Type}, {"Q120I", Int64.Type}, {"Q120E", Int64.Type}, {"Q121A", Int64.Type}, {"Q121I", Int64.Type}, {"Q121E", Int64.Type}, {"Q122A", Int64.Type}, {"Q122I", Int64.Type}, {"Q122E", Int64.Type}, {"Q123A", Int64.Type}, {"Q123I", Int64.Type}, {"Q123E", Int64.Type}, {"Q124A", Int64.Type}, {"Q124I", Int64.Type}, {"Q124E", Int64.Type}, {"Q125A", Int64.Type}, {"Q125I", Int64.Type}, {"Q125E", Int64.Type}, {"Q126A", Int64.Type}, {"Q126I", Int64.Type}, {"Q126E", Int64.Type}, {"Q127A", Int64.Type}, {"Q127I", Int64.Type}, {"Q127E", Int64.Type}, {"Q128A", Int64.Type}, {"Q128I", Int64.Type}, {"Q128E", Int64.Type}, {"Q129A", Int64.Type}, {"Q129I", Int64.Type}, {"Q129E", Int64.Type}, {"Q130A", Int64.Type}, {"Q130I", Int64.Type}, {"Q130E", Int64.Type}, {"Q131A", Int64.Type}, {"Q131I", Int64.Type}, {"Q131E", Int64.Type}, {"Q132A", Int64.Type}, {"Q132I", Int64.Type}, {"Q132E", Int64.Type}, {"Q133A", Int64.Type}, {"Q133I", Int64.Type}, {"Q133E", Int64.Type}, {"Q134A", Int64.Type}, {"Q134I", Int64.Type}, {"Q134E", Int64.Type}, {"Q135A", Int64.Type}, {"Q135I", Int64.Type}, {"Q135E", Int64.Type}, {"Q136A", Int64.Type}, {"Q136I", Int64.Type}, {"Q136E", Int64.Type}, {"Q137A", Int64.Type}, {"Q137I", Int64.Type}, {"Q137E", Int64.Type}, {"Q138A", Int64.Type}, {"Q138I", Int64.Type}, {"Q138E", Int64.Type}, {"Q139A", Int64.Type}, {"Q139I", Int64.Type}, {"Q139E", Int64.Type}, {"Q140A", Int64.Type}, {"Q140I", Int64.Type}, {"Q140E", Int64.Type}, {"Q141A", Int64.Type}, {"Q141I", Int64.Type}, {"Q141E", Int64.Type}, {"Q142A", Int64.Type}, {"Q142I", Int64.Type}, {"Q142E", Int64.Type}, {"Q143A", Int64.Type}, {"Q143I", Int64.Type}, {"Q143E", Int64.Type}, {"Q144A", Int64.Type}, {"Q144I", Int64.Type}, {"Q144E", Int64.Type}, {"Q145A", Int64.Type}, {"Q145I", Int64.Type}, {"Q145E", Int64.Type}, {"Q146A", Int64.Type}, {"Q146I", Int64.Type}, {"Q146E", Int64.Type}, {"Q147A", Int64.Type}, {"Q147I", Int64.Type}, {"Q147E", Int64.Type}, {"Q148A", Int64.Type}, {"Q148I", Int64.Type}, {"Q148E", Int64.Type}, {"Q149A", Int64.Type}, {"Q149I", Int64.Type}, {"Q149E", Int64.Type}, {"Q150A", Int64.Type}, {"Q150I", Int64.Type}, {"Q150E", Int64.Type}, {"Q151A", Int64.Type}, {"Q151I", Int64.Type}, {"Q151E", Int64.Type}, {"Q152A", Int64.Type}, {"Q152I", Int64.Type}, {"Q152E", Int64.Type}, {"Q153A", Int64.Type}, {"Q153I", Int64.Type}, {"Q153E", Int64.Type}, {"Q154A", Int64.Type}, {"Q154I", Int64.Type}, {"Q154E", Int64.Type}, {"Q155A", Int64.Type}, {"Q155I", Int64.Type}, {"Q155E", Int64.Type}, {"Q156A", Int64.Type}, {"Q156I", Int64.Type}, {"Q156E", Int64.Type}, {"Q157A", Int64.Type}, {"Q157I", Int64.Type}, {"Q157E", Int64.Type}, {"Q158A", Int64.Type}, {"Q158I", Int64.Type}, {"Q158E", Int64.Type}, {"Q159A", Int64.Type}, {"Q159I", Int64.Type}, {"Q159E", Int64.Type}, {"Q160A", Int64.Type}, {"Q160I", Int64.Type}, {"Q160E", Int64.Type}, {"Q161A", Int64.Type}, {"Q161I", Int64.Type}, {"Q161E", Int64.Type}, {"Q162A", Int64.Type}, {"Q162I", Int64.Type}, {"Q162E", Int64.Type}, {"Q163A", Int64.Type}, {"Q163I", Int64.Type}, {"Q163E", Int64.Type}, {"Q164A", Int64.Type}, {"Q164I", Int64.Type}, {"Q164E", Int64.Type}, {"Q165A", Int64.Type}, {"Q165I", Int64.Type}, {"Q165E", Int64.Type}, {"Q166A", Int64.Type}, {"Q166I", Int64.Type}, {"Q166E", Int64.Type}, {"Q167A", Int64.Type}, {"Q167I", Int64.Type}, {"Q167E", Int64.Type}, {"Q168A", Int64.Type}, {"Q168I", Int64.Type}, {"Q168E", Int64.Type}, {"Q169A", Int64.Type}, {"Q169I", Int64.Type}, {"Q169E", Int64.Type}, {"Q170A", Int64.Type}, {"Q170I", Int64.Type}, {"Q170E", Int64.Type}, {"Q171A", Int64.Type}, {"Q171I", Int64.Type}, {"Q171E", Int64.Type}, {"Q172A", Int64.Type}, {"Q172I", Int64.Type}, {"Q172E", Int64.Type}, {"Q173A", Int64.Type}, {"Q173I", Int64.Type}, {"Q173E", Int64.Type}, {"Q174A", Int64.Type}, {"Q174I", Int64.Type}, {"Q174E", Int64.Type}, {"Q175A", Int64.Type}, {"Q175I", Int64.Type}, {"Q175E", Int64.Type}, {"Q176A", Int64.Type}, {"Q176I", Int64.Type}, {"Q176E", Int64.Type}, {"Q177A", Int64.Type}, {"Q177I", Int64.Type}, {"Q177E", Int64.Type}, {"Q178A", Int64.Type}, {"Q178I", Int64.Type}, {"Q178E", Int64.Type}, {"Q179A", Int64.Type}, {"Q179I", Int64.Type}, {"Q179E", Int64.Type}, {"Q180A", Int64.Type}, {"Q180I", Int64.Type}, {"Q180E", Int64.Type}, {"Q181A", Int64.Type}, {"Q181I", Int64.Type}, {"Q181E", Int64.Type}})
in
    #"Changed Type"
